---
API_TOKEN: f7TVSYoYOWc3AeeXlwio1E3F
USERNAME: ruchi.sharma@bazaarvoice.com
DOMAIN: bazaarvoice
PROJECT_KEY: PD
DESCRIPTION: "Create UAT ticket"
ISSUETYPE: Task
SUMMARY: "Create tickets for UAT and prod deployments"
